### PR TITLE
feat: Completeness#146

### LINKED ISSUE #146: Newly structure the dls page.
### Problem

Page could be better organised 

### Desired Solution

Title in bold on the top center
Make a box/frame around map and data
Put data date on lower right
Check on which Computer/Phone/Tablet it should run.

### Considered Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yokat**
## Description

added new file with heatmap view of reports similar to "Completeness".  However, it is only for reports as information about the completeness reference is missing.
Adjusted home page for correct additional link
Visualization of reporting status was requested.

closes #146
relates road86/repository_name#146

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the road86 Contribution Guide.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have assigned at least one reviewer.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.

### CODE REVIEW

**Comment by mixmixmix** [comment]
Reports dynamic headers do not fully show
Screenshot 2023-07-22 at 14 53 39

**Review by mixmixmix — CHANGES_REQUESTED** [review]
as per above comment, see what can be easily improved,.

**Comment by yokat** [comment]
ugh, quite some old stuff. good trainings against my dementia.
Changed 1 and 5
2 is shown in "previous" tab "reports per geolocation". should it be shown in that other one again?
3 Sorry, I am a sloppy language user. Any suggestion how to rename?
4 is raised, most likely because there is no data somewhere. I haven't caught every empty variables. I can see, what I might be able to do in short time.

**Comment by mixmixmix** [comment]
> 2 is shown in "previous" tab "reports per geolocation". should it be shown in that other one again?
Rather yes. People will like to have things on one screen - some might prefer one view, some another - but if `0` is number of reports it is still a valid datapoint ;)

> 3 Sorry, I am a sloppy language user. Any suggestion how to rename?
e.g. `Reports Chart` and `Reports Table` - both are showing reports per geolocation after all.

> 4 is raised, most likely because there is no data somewhere. I haven't caught every empty variables. I can see, what I might be able to do in short time.
no problem, just wanted you to know.

new points (but without reloading the code with most recent changes yet) - just realised I missed actual completeness matrix :D

6. DD - page not found. Not sure if it worked locally, but doesn't on the server
Screenshot 2023-07-24 at 07 57 01

Screenshot 2023-07-24 at 07 57 20
7. colour scheme
I suggest colour scheme goes from red to green (or any two colours) otherwise it is difficult to watch with such bright colour. 
8. There need to be an explanation (maybe below) how to understand the data
9. time is in v. technical format eg. `y2022w43` should be just Week number and only for current year, or some overall year heading so it isn't unnecessarily repeated in each column heading
10. Are percentages calculated assuming one report per week is a 100% reporting? I think it should be more sth like "100% reporting is defined as five days with at least one report in a given week", so any more than 5 reporting days is still 100, but 5 on one day is only 20%.

**Comment by yokat** [comment]
outdated, overtaken by other branches

**Pull request closed without merging**
