### PR TITLE
feat: Update ULO.py fix of #63 showing dates upon start 

### LINKED ISSUE #63: ULO should show matching date range from data after loading
### Bug Description

The data is loaded, but the daterange is not showing the dates.

### To Reproduce

4. See error.

### Expected Behaviour

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yokat**
fixed

## Description

Two(lines) were inserted to update of dates in the UI

closes #63 
relates road86/repository_name#issue_number

- [ ] I have read the road86 Contribution Guide.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.

### CODE REVIEW

**Comment by yokat** [comment]
Corrections needed for general data matches. E.g. selecting diseases reduce the date range and should be represented too as the graph shows the modification

**Comment by mixmixmix** [comment]
@yokat is this mean to be closed?

**Comment by yokat** [comment]
History is, I meant this PR to fix issues
(When selecting down to upazila, the date range was not showing any dates, although the range was correctly limited to what the dataframe provided. Was more a cosmetic topic, to show the user, also the date range on time)
, but realised this was not the solution. Therefore I closed it first. I got confused, because the issue was still existing, but at the end the other branch solved this issue. So whenever in ULO.py, the geolocation until upazila is selected, it shows the existing date range for that upazila.

**Comment by yokat** [comment]
So this PR can be deleted/closed.

**Pull request closed without merging**
